import Head from "next/head";
import Navigation from "./Components/Navigation/Nav";
import styles from "../styles/Home.module.css";
import MainContent from "./Components/Hero";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
      <main className={styles.main}>
        <h1>COMA CLAN</h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://jimenez.tech"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by jimenez.tech
        </a>
      </footer>
    </div>
  );
}
